"""Friend requests

Revision ID: 0455e92324fc
Revises: 4b055cd79cd3
Create Date: 2024-11-03 11:38:58.915758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0455e92324fc'
down_revision: Union[str, None] = '4b055cd79cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_requests',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('initiator_id', sa.Integer(), nullable=True, comment='User, who want to add to friend'),
        sa.Column('receiver_id', sa.Integer(), nullable=True, comment='Reciever of friend request'),
        sa.Column('status', sa.Integer(), nullable=False, comment='Status of request'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('status IN (0, 1, 2)', name='check_status'),
        sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('initiator_id', 'receiver_id', name='uq_initiator_receiver')
    )
    op.create_index(op.f('ix_friend_requests_id'), 'friend_requests', ['id'], unique=False)
    op.create_index(op.f('ix_friend_requests_initiator_id'), 'friend_requests', ['initiator_id'], unique=False)
    op.create_index(op.f('ix_friend_requests_receiver_id'), 'friend_requests', ['receiver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friend_requests_receiver_id'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_initiator_id'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_id'), table_name='friend_requests')
    op.drop_table('friend_requests')
    # ### end Alembic commands ###
