"""Initial

Revision ID: 40f6becd5e37
Revises: 
Create Date: 2024-11-01 06:56:04.946266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f6becd5e37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(), nullable=True, comment='Title of chat'),
        sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='Soft delete for model'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_index(op.f('ix_chats_title'), 'chats', ['title'], unique=True)
    op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(), nullable=True, comment='The username chosen by the user'),
        sa.Column('email', sa.String(), nullable=True, comment="User's email address"),
        sa.Column('password', sa.String(length=255), nullable=True, comment="User's password"),
        sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='Soft delete for model'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_events',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('chat_id', sa.Integer(), nullable=True, comment="Event's chat"),
        sa.Column('initiator_id', sa.Integer(), nullable=True, comment="Event's initiator. Sender of message"),
        sa.Column('receiver_id', sa.Integer(), nullable=True, comment="Event's receiver. Receiver of message"),
        sa.Column('type', sa.Enum('MESSAGE', 'CALL', name='chateventtype'), nullable=False, comment='Type of event'),
        sa.Column('browsed', sa.Boolean(), nullable=True, comment='If receiver of event browsed this event'),
        sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='Soft delete for model'),
        sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
        sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_events_id'), 'chat_events', ['id'], unique=False)
    op.create_table('friends_association',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('friend_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('users_association',
        sa.Column('user_id', sa.Integer(), nullable=False, comment='User in chat'),
        sa.Column('chat_id', sa.Integer(), nullable=False, comment='Chat'),
        sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.create_table('browsed_users',
        sa.Column('user_id', sa.Integer(), nullable=False, comment='User in chat'),
        sa.Column('event_id', sa.Integer(), nullable=False, comment='Chat event'),
        sa.ForeignKeyConstraint(['event_id'], ['chat_events.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.create_table('events_association',
        sa.Column('event_id', sa.Integer(), nullable=False, comment="Chat's event"),
        sa.Column('chat_id', sa.Integer(), nullable=False, comment='Chat'),
        sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
        sa.ForeignKeyConstraint(['event_id'], ['chat_events.id'], ),
        sa.PrimaryKeyConstraint('event_id', 'chat_id')
    )
    op.create_table('messages',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=True, comment="Message's event"),
        sa.Column('message', sa.String(), nullable=True, comment='Message content'),
        sa.ForeignKeyConstraint(['event_id'], ['chat_events.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('attachments',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('path', sa.String(), nullable=True, comment='Resource path'),
        sa.Column('type', sa.Enum('PHOTO', 'VIDEO', name='attachmentenum'), nullable=False, comment='Type of attachment'),
        sa.Column('message_id', sa.Integer(), nullable=True, comment="Attachment's message"),
        sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='Soft delete for model'),
        sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    op.create_index(op.f('ix_attachments_path'), 'attachments', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_path'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('events_association')
    op.drop_table('browsed_users')
    op.drop_table('users_association')
    op.drop_table('friends_association')
    op.drop_index(op.f('ix_chat_events_id'), table_name='chat_events')
    op.drop_table('chat_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_chats_title'), table_name='chats')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
