"""Reset token model

Revision ID: 4b055cd79cd3
Revises: 40f6becd5e37
Create Date: 2024-11-01 13:12:47.370176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b055cd79cd3'
down_revision: Union[str, None] = '40f6becd5e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_tokens',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('token', sa.String(), nullable=True, comment='Reset token value'),
        sa.Column('expired_date', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True, comment='User, who reset password'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reset_tokens_id'), 'reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_reset_tokens_token'), 'reset_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reset_tokens_token'), table_name='reset_tokens')
    op.drop_index(op.f('ix_reset_tokens_id'), table_name='reset_tokens')
    op.drop_table('reset_tokens')
    # ### end Alembic commands ###
