version: '3.9'

services:
  chat:
    container_name: chat_api
    build:
      context: ../../..
      dockerfile: build_env/docker-compose/local/Dockerfile
    command: ash -c "python main.py"
    volumes:
      - ../../../app:/usr/src/app/
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: chat_db
    image: postgres:14-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
